INSERT INTO games (id, name, image, team_max_nr)
VALUES ('1', 'League of Legends', 'lol-logo.png', 10),
       ('2', 'Counter-Strike 2', 'cs2-logo.png', 10),
       ('3', 'Valorant', 'valorant-logo.png', 10),
       ('4', 'Dota 2', 'dota2-logo.png', 10),
       ('5', 'Overwatch 2', 'overwatch2-logo.png', 10),
       ('6', 'Rocket League', 'rocket-league-logo.png', 10),
       ('7', 'Rainbow Six Siege', 'r6siege-logo.png', 10),
       ('8', 'FIFA 24', 'fifa24-logo.png', 10),
       ('9', 'Apex Legends', 'apex-legends-logo.png', 10),
       ('10', 'PUBG', 'pubg-logo.png', 10),
       ('11', 'Hearthstone', 'hearthstone-logo.png', 10),
       ('12', 'Fortnite', 'fortnite-logo.png', 10),
       ('13', 'Team Fight Tactics', 'tft-logo.png', 10),
       ('14', 'Call of Duty: Warzone', 'warzone-logo.png', 10),
       ('15', 'StarCraft II', 'starcraft2-logo.png', 10);